### ISSUE TITLE
Why stop it to update?

### ISSUE THREAD

**Issue by tim-hub** [pslusarz/gnubridge#1]
I think it is pretty cool.

**Comment by brynne8** [comment]
@pslusarz  It's the only open source contract bridge game I've ever seen. Why not strengthen the bidding section? My bridge teacher said bidding is very important. Does GNUBridge bid SAYC system? Singletons can be autoplayed. If we can undo our played cards, we may enjoy the game better.

**Comment by pslusarz** [comment]
Sorry, I haven't been checking the issue tracker, so this reply comes months after your comments. Gnubridge only bids according to the first few Pavlicek lessons. Singletons are autoplayed, but to avoid revealing that the computer has no cards left, there's a random timer. I do not consider undo to be a worthwhile option. If I'm in the GUI again, I'll work on smoothing out the mechanics and adding subtle animation effects to draw player attention to what's happening. I'd like Gnubridge to follow a minimalistic feature philosophy.
While bidding is indeed the single sore spot for players, I do not find it interesting to work on. There's a framework in place and people can add rules to it if they wish. At this point, my priority is a solid double dummy solver engine.

**Comment by brynne8** [comment]
@pslusarz I noticed you've recently returned to the GNUBridge project. I wanted to mention that I previously created a fork of GNUBridge at https://github.com/brynne8/gnubridge. While I've largely forgotten both bridge gameplay and my own code from that time, I'd be happy if any of my previous work could be helpful to you.

My contributions focused on two main areas:

1. **Bidding System Enhancements**  
   I implemented several widely-used bidding conventions including:
   - Stayman
   - Minor Suit Stayman
   - Two-over-One Game Forcing
   - Jacoby Transfer
   - Forcing 1NT
   - Inverted Minor
   - Takeout Double
   - Weak Two
   - Preempt
   
   These modifications were aimed at making the bidding process more rational and information-rich.

2. **Double-Dummy Solver Modifications**  
   I also worked on modifying the Double-Dummy solver after noticing that the original solver would sometimes take an excessive amount of time to produce results in certain situations. However, I should note that my solver implementation wasn't completely stabilized at the time.

While I may not be actively involved with bridge nowadays, please feel free to review any of these implementations if they could benefit the current development of GNUBridge.

**Comment by pslusarz** [comment]
Hi @brynne8 . Thanks for the heads up. I'd need thorough unit tests before being able to merge your bidding changes.
